[HARDWARE]
;template=E:\VHDs\TMPLG2-2019.vhdx
;diskpath=F:\Virtual Disks\
;vmpath=F:\Virtual Machines\
;unattend=E:\SourceFiles\unattend.xml
;generation=2
ram=3
;switch=Production


[UPGRADES]
vcpu=2


[POSTCONFIG]
localpw=Password1@nait.ca
joindomain=no
sw=NET-Framework-Features,NET-Framework-45-ASPNET,Web-Server,Web-App-Dev,Web-Mgmt-Tools
